name: My First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, welcome!"
      - name: Print closing message
        run: echo "Done - Ciao!!"
